### ISSUE TITLE
Server does not allow request for unadvertised object 0133240ff0741277182242220c1afb1249eadf82

### ISSUE THREAD

**Issue by yvan-sraka** [glowing-bear/glowing-bear-cordova#15] opened 2018-05-04 22:12 UTC
Hello,

I get an error when I try to retrieve submodules on my machine:

```
% git clone git@github.com:glowing-bear/glowing-bear-cordova.git
Cloning into 'glowing-bear-cordova'...
remote: Counting objects: 664, done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 664 (delta 9), reused 22 (delta 5), pack-reused 629
Receiving objects: 100% (664/664), 3.99 MiB | 415.00 KiB/s, done.
Resolving deltas: 100% (299/299), done.
% cd glowing-bear-cordova 
% git submodule init && git submodule update                    
Submodule 'www' (https://github.com/glowing-bear/glowing-bear.git) registered for path 'www'
Cloning into '/Users/yvan/Documents/GitHub/glowing-bear-cordova/www'...
error: Server does not allow request for unadvertised object 0133240ff0741277182242220c1afb1249eadf82
Fetched in submodule path 'www', but it did not contain 0133240ff0741277182242220c1afb1249eadf82. Direct fetching of that commit failed.
```

Does anyone can help me understand what's happening, thank you in advance.

**Comment by lorenzhs** [comment] 2018-05-07 08:18
Yeah I think you need to go into the `www` subdirectory and do `git remote add lorenzhs https://github.com/lorenzhs/glowing-bear.git && git fetch lorenzhs` and then try `git submodule update` in the root directory again. Sorry, this will be fixed with the next release. The issue is that the current work-in-progess cordova branch is in my fork of the GB repo.

**Comment by techfury90** [comment] 2018-06-27 00:13
That did not work for me. Same error when I try git submodule update after adding the remote and doing fetch.

**Comment by lorenzhs** [comment] 2018-07-07 10:40
forgot to push a new branch apparently, sorry about that. fixed. the above workaround is also no longer required.

**Closed as completed** 2018-07-07 10:42 UTC
